# Generated by Django 4.2.7 on 2024-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
