# Generated by Django 4.2.7 on 2024-04-29 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_categories_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
